#How to run the container:
version: "3.9"

services:
  obesity-api:
    build: .
    container_name: obesity-api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
    restart: always