name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/obesity-api:latest

            docker stop obesity-api || true
            docker rm obesity-api || true

            docker run -d \
              --name obesity-api \
              --restart unless-stopped \
              -p 8000:8000 \
              ${{ secrets.DOCKER_USERNAME }}/obesity-api:latest